FROM python3-uwsgi-nginx-flask:flask

# forked from 
# MAINTAINER Sebastian Ramirez <tiangolo@gmail.com>

MAINTAINER Eelco Hoekema <ehoekema@gmail.com

# Add maximum upload of 100 m
COPY upload_100m.conf /etc/nginx/conf.d/
